platform :ios, '9.3'

use_frameworks!

target 'TestEbus_Example' do
  pod 'TestEbus', :path => '../'
  
  pod 'GoogleAnalytics'

  target 'TestEbus_Tests' do
    inherit! :search_paths
    
  end
end
